on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: dbservice

jobs:
  create:
    name: build-dbservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_ecr_central_pub }}
          aws-secret-access-key: ${{ secrets.aws_ecr_central_priv }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image-back
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: back
          IMAGE_TAG: ${{ github.run_id }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:back-$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:back-latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:back-$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:back-latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:back-$IMAGE_TAG"
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:back-latest"
